### ISSUE TITLE
Think about how to pass the analyse to thread process

### ISSUE THREAD

**Issue by mcjpedro** [mrdrzit/Behavython#20]
https://github.com/mrdrzit/Behavython/blob/8df4e11df8857e4a45b70fd9330fb265b18106fe/behavython_back.py#L47

**Comment by mrdrzit** [comment]
This issue ws solved in the last update 
cmmit = 87a516ee24aeae42f70482f40fb0a38dda9abfd0

**Comment by mrdrzit** [comment]
This issue ws solved in the last update 
cmmit = 87a516ee24aeae42f70482f40fb0a38dda9abfd0
